import * as React from 'react';
import ReactDOM from 'react-dom';
import { Button } from reactstrap;
import myform from './myform'
export function uniqID() {
    let i = Math.random().toString(16).slice(2);
    return (<Button id={i} />);

}

ReactDOM.render(
    // style={{ textAlign: 'center' }}
    <section style={{ textAlign: 'center' }}>
        <uniqID />
    </section>,

    document.getElementById('autogenerated'));